- name: Setup HTTP Server
  hosts: main-server
  user: fedora

  tasks:

    - name: install the latest version of Apache server
      dnf:
        name: httpd
        state: latest
      become: true

    - service:
        name: httpd
        state: started
      become: true

  # Add your tasks here