- name: Setup HTTP Server
  hosts: main-server
  user: fedora
  become: yes

  tasks:

    - name: install the latest version of Apache server
      dnf:
        name: httpd
        state: latest

    - service:
        name: httpd
        state: started

  # Add your tasks here