- name: Setup HTTP Server
  hosts: main-server
  user: nbalkiss 
  become: yes

  tasks:

    - name: install the latest version of Apache server
      yum:
        name: httpd
        state: latest

    - service:
        name: httpd
        state: started

  # Add your tasks here
